# Users Configuration
user_1:
  name: "Peter"
  yes_button: "y"
  no_button: "c"

user_2:
  name: "Camille"  # leave empty for a single user
  yes_button: "1"
  no_button: "3"

# Name of the file where the results are saved
results_file: results.csv